// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/nguyen-quang-phu/go-ecommerce-backend-api/internal/controllers"
	"github.com/nguyen-quang-phu/go-ecommerce-backend-api/internal/repo"
	"github.com/nguyen-quang-phu/go-ecommerce-backend-api/internal/services"
)

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controllers.UserController, error) {
	iUserRepository := repo.NewUserRepository()
	iUserAuthRepository := repo.NewUserAuthRepository()
	iUserService := service.NewUserService(iUserRepository, iUserAuthRepository)
	userController := controllers.NewUserController(iUserService)
	return userController, nil
}
