server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root1234
  dbname: shopdevgo
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
logger:
  log_level: debug
  file_name: "./storages/logs/dev.001.log"
  max_size: 500 # megabytes
  max_backups: 3
  max_age: 28 # days
  compress: true # disabled by default
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 10
