server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
log:
  logLevel: debug
  fileName: "./storages/logs/dev.001.log"
  maxSize: 500 # megabytes
  maxBackups: 3
  maxAge: 28 # days
  compress: true # disabled by default
